
 -- 5 PREMIOS NOBEL MAS RECIENTES
SELECT *
 FROM DANIELYN.NOBEL 
 INNER JOIN DANIELYN.YEAR yr ON DANIELYN.NOBEL.NOBEL_ID = yr.YEAR_ID WHERE yr.YEAR_ID > 5;
 
 -- ultimos 10 premios nobel de fisica
 
 SELECT *
 FROM DANIELYN.NOBEL 
 INNER JOIN DANIELYN.YEAR yr ON DANIELYN.NOBEL.NOBEL_ID = yr.YEAR_ID WHERE yr.YEAR_ID > 5;
 
--10 PREMIOS NOBEL DE FISICA
 SELECT *
 FROM DANIELYN.CATEGORY 
 INNER JOIN DANIELYN.YEAR yr ON DANIELYN.CATEGORY.CATEGORY_ID= yr.YEAR_ID WHERE yr.YEAR_ID > 10;
 
 --personas que han ganado mas de un premio
 SELECT *
 FROM DANIELYN.CANDIDATE
 INNER JOIN DANIELYN.CATEGORY cat ON DANIELYN.CANDIDATE.ROLE = cat.CATEGORY_ID
  INNER JOIN DANIELYN.YEAR y ON DANIELYN.CANDIDATE.ROLE = y.YEAR_ID;

 --lenguaje con mas premios
 SELECT *
 FROM DANIELYN.NOBEL
 INNER JOIN DANIELYN.CATEGORY cate ON DANIELYN.NOBEL.CATEGORY = cate.LANGUAGE;

 
 --- premios ganados desde el año 1980 al 1990 en quimica:
SELECT *
    FROM DANIELYN.YEAR
INNER JOIN DANIELYN.NOBEL nob ON DANIELYN.YEAR.YEAR_ID = nob.PRIZE_NAME
   WHERE EXTRACT (YEAR FROM YEAR) = 1980;
   
-- premio nobel ganado menos ocasiones
SELECT * 
FROM DANIELYN.YEAR
INNER JOIN DANIELYN.CATEGORY categ ON DANIELYN.YEAR.YEAR_ID = categ.CATEGORY_ID
WHERE EXTRACT (YEAR FROM YEAR) < 1;

--obtener el pais con mas premios nobel
SELECT * 
FROM DANIELYN.COUNTRY
INNER JOIN DANIELYN.CATEGORY c ON DANIELYN.COUNTRY.COUNTRY_ID = c.CATEGORY_ID
INNER JOIN DANIELYN.YEAR y ON DANIELYN.COUNTRY.COUNTRY_ID = y.YEAR_ID
WHERE EXTRACT (YEAR FROM YEAR) > 1;

--premios nobel compartidos 
SELECT *
FROM DANIELYN.CANDIDATE
INNER JOIN DANIELYN.CATEGORY categ ON DANIELYN.CANDIDATE.ROLE = categ.CATEGORY_ID
INNER JOIN DANIELYN.YEAR yr ON DANIELYN.CANDIDATE.NAME = yr.YEAR_ID
WHERE EXTRACT 
   