ALTER TABLE DANIELYN.CANDIDATE ADD 
CONSTRAINT CANDIDATE_R01
 FOREIGN KEY (CANDIDATE_ID)
 REFERENCES DANIELYN.NOBEL (NOBEL_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.PRIZE ADD 
CONSTRAINT PRIZE_R01
 FOREIGN KEY (NOBEL_ID)
 REFERENCES DANIELYN.CATEGORY (CATEGORY_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.ORIGIN ADD 
CONSTRAINT ORIGIN_R01
 FOREIGN KEY (ORIGIN_ID)
 REFERENCES DANIELYN.CANDIDATE (CANDIDATE_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.CATEGORY ADD 
CONSTRAINT CATEGORY_R01
 FOREIGN KEY (CATEGORY_ID)

ALTER TABLE DANIELYN.BIRTHPLACE ADD 
CONSTRAINT BIRTHPLACE_R01
 FOREIGN KEY (BIRTHPLACE_ID)
 REFERENCES DANIELYN.CANDIDATE (CANDIDATE_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.COUNTRY ADD 
CONSTRAINT COUNTRY_R01
 FOREIGN KEY (COUNTRY_ID)
 REFERENCES DANIELYN.ORIGIN (ORIGIN_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.YEAR ADD 
CONSTRAINT YEAR_R01
 FOREIGN KEY (YEAR_ID)
 REFERENCES DANIELYN.NOBEL (NOBEL_ID)
 ENABLE

ALTER TABLE DANIELYN.YEAR ADD 
CONSTRAINT YEAR_R02
 FOREIGN KEY (YEAR_ID)
 REFERENCES DANIELYN.PRIZE (NOBEL_ID)
 ENABLE
 VALIDATE;
 VALIDATE;
 REFERENCES DANIELYN.NOBEL (NOBEL_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.CATEGORY ADD 
CONSTRAINT CATEGORY_R02
 FOREIGN KEY (CATEGORY_ID)
 REFERENCES DANIELYN.PRIZE (NOBEL_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.PLACE ADD 
CONSTRAINT PLACE_R01
 FOREIGN KEY (PLACE_ID)
 REFERENCES DANIELYN.CANDIDATE (CANDIDATE_ID)
 ENABLE
 VALIDATE;

ALTER TABLE DANIELYN.MOTIVATION ADD 
CONSTRAINT MOTIVATION_R01
 FOREIGN KEY (MOTIVATION_ID)
 REFERENCES DANIELYN.CANDIDATE (CANDIDATE_ID)
 ENABLE
 VALIDATE;