CREATE OR REPLACE FUNCTION EXI_023664.YEARS (EDAD1 IN DATE)
    RETURN NUMBER
AS
    AÑOS   NUMBER;
BEGIN
    SELECT FLOOR (MONTHS_BETWEEN (SYSDATE, EDAD1) / 12) INTO AÑOS FROM DUAL;

    RETURN AÑOS;
END YEARS;

SELECT WIN.WINNER_NAME, EXI_023664.YEAR (WIN.BIRTHDATE) Años
  FROM EXI_023664.WINNER WIN;
  
CREATE OR REPLACE FUNCTION EXI_023664.YEAR2 (EDAD1 IN DATE, EDAD2 IN DATE)
    RETURN NUMBER
AS
    AÑOS   NUMBER;
BEGIN
    SELECT FLOOR (MONTHS_BETWEEN (EDAD2, EDAD1) / 12) INTO AÑOS FROM DUAL;

    RETURN AÑOS;
END YEAR2;